[linters]
  enable-all = true
  disable = [
    "lll",
    "goerr113",
    "noctx",
    "gomnd",
    "gochecknoglobals",
    "exhaustivestruct",
    "funlen"
  ]

[issues]
    exclude-use-default = true